# Train Models

In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np

# do not print warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
# the training and test data is loaded 
train_set = pd.read_excel("train_set1.xlsx", index_col = 0)
test_set = pd.read_excel("test_set1.xlsx", index_col = 0)

In [3]:
train_set.head()

,Real_GDP,Exchange_Rate,Long_Term_Interest_Rates,Current_Account_Balance,Unemployment_Rate,Inflation,Population,Corporate_Tax_Rate,Trade_Openess,Administrative_and_support_service_activities,...,Spain,Sweden,Switzerland,"Taipei, Chinese",Thailand,Turkey,United States of America,Uruguay,"Venezuela, Bolivarian Republic of",FDI
0,-1.074346,1.448440,-1.182601,1.933870,-1.142748,1.279434,1.346033,-1.175126,1.339870,-0.189838,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,0.00
1,1.559353,-1.187126,1.266403,-0.716267,0.456704,-0.073626,-0.729335,0.305369,-0.482947,-0.189838,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,1.59
2,-0.163390,-0.689887,0.937059,-0.092447,1.713947,0.910418,-1.435507,1.785864,0.947761,-0.189838,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,0.00
3,1.559353,-1.187126,1.266403,-0.716267,0.456704,-0.073626,-0.729335,0.305369,-0.482947,-0.189838,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,6.245823,-0.089733,-0.09118,660.80
4,1.559353,-1.187126,1.266403,-0.716267,0.456704,-0.073626,-0.729335,0.305369,-0.482947,-0.189838,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,0.00

# Create subset

In [4]:
train_set.Financial_and_insurance_activities

0      -0.245729
1      -0.245729
2      -0.245729
3      -0.245729
4      -0.245729
5      -0.245729
6      -0.245729
7      -0.245729
8      -0.245729
9      -0.245729
10     -0.245729
11     -0.245729
12     -0.245729
13     -0.245729
14     -0.245729
15     -0.245729
16     -0.245729
17     -0.245729
18     -0.245729
19     -0.245729
20     -0.245729
21     -0.245729
22     -0.245729
23     -0.245729
24     -0.245729
25     -0.245729
26     -0.245729
27     -0.245729
28     -0.245729
29     -0.245729
          ...
3851   -0.245729
3852   -0.245729
3853   -0.245729
3854   -0.245729
3855   -0.245729
3856   -0.245729
3857   -0.245729
3858    4.069531
3859   -0.245729
3860   -0.245729
3861   -0.245729
3862   -0.245729
3863   -0.245729
3864   -0.245729
3865   -0.245729
3866   -0.245729
3867   -0.245729
3868   -0.245729
3869   -0.245729
3870   -0.245729
3871   -0.245729
3872   -0.245729
3873   -0.245729
3874   -0.245729
3875   -0.245729
3876   -0.245729
3877   -0.245729
3878   -0.245729
3879   -0.245729
3880   -0.245729
Name: Financial_and_insurance_activities, Length: 3881, dtype: float64

In [5]:
model_train = train_set[train_set.Financial_and_insurance_activities > -0.245]
model_test = test_set[test_set.Financial_and_insurance_activities > -0.245]

In [6]:
model_train.head()

,Real_GDP,Exchange_Rate,Long_Term_Interest_Rates,Current_Account_Balance,Unemployment_Rate,Inflation,Population,Corporate_Tax_Rate,Trade_Openess,Administrative_and_support_service_activities,...,Spain,Sweden,Switzerland,"Taipei, Chinese",Thailand,Turkey,United States of America,Uruguay,"Venezuela, Bolivarian Republic of",FDI
31,0.630904,-0.458109,0.039306,-0.660447,-0.272349,-1.426685,0.008478,-0.434879,-1.364292,-0.189838,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,680.35
64,-0.977965,0.882495,-1.055125,-0.489710,-0.718707,-0.688653,0.782246,-0.434879,-0.431557,-0.189838,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,0.00
78,0.630904,-0.458109,0.039306,-0.660447,-0.272349,-1.426685,0.008478,-0.434879,-1.364292,-0.189838,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,1215.80
85,-1.074346,1.448440,-1.182601,1.933870,-1.142748,1.279434,1.346033,-1.175126,1.339870,-0.189838,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,-0.68
86,0.630904,-0.458109,0.039306,-0.660447,-0.272349,-1.426685,0.008478,-0.434879,-1.364292,-0.189838,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,0.00

In [7]:
model_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 221 entries, 31 to 3858
Data columns (total 95 columns):
Real_GDP                                                                   221 non-null float64
Exchange_Rate                                                              221 non-null float64
Long_Term_Interest_Rates                                                   221 non-null float64
Current_Account_Balance                                                    221 non-null float64
Unemployment_Rate                                                          221 non-null float64
Inflation                                                                  221 non-null float64
Population                                                                 221 non-null float64
Corporate_Tax_Rate                                                         221 non-null float64
Trade_Openess                                                              221 non-null float64
Administrative_and_support_service_activities                              221 non-null float64
Advertising_and_market_research                                            221 non-null float64
Architectural_and_engineering_activities_technical_testing_and_analysis    221 non-null float64
Computer_programming_consultancy_and_related_activities                    221 non-null float64
Construction                                                               221 non-null float64
Education                                                                  221 non-null float64
Extraction_of_crude_petroleum_and_natural_gas                              221 non-null float64
Financial_and_insurance_activities                                         221 non-null float64
Information_and_communication                                              221 non-null float64
Legal_and_accounting_activities                                            221 non-null float64
Management_consultancy_activities                                          221 non-null float64
Manufacture_of_chemicals_and_chemical_products                             221 non-null float64
Manufacture_of_computer_electronic_and_optical_products                    221 non-null float64
Manufacture_of_food_products                                               221 non-null float64
Manufacture_of_motor_vehicles_trailers_and_semi_trailers                   221 non-null float64
Mining_and_quarrying                                                       221 non-null float64
Professional_scientific_and_technical_activities                           221 non-null float64
Real_estate_activities                                                     221 non-null float64
Scientific_research_and_development                                        221 non-null float64
Telecommunications                                                         221 non-null float64
Transportation_and_storage                                                 221 non-null float64
Wholesale_and_retail_trade_and_repair_of_motor_vehicles_and_motorcycles    221 non-null float64
2014                                                                       221 non-null float64
2015                                                                       221 non-null float64
2016                                                                       221 non-null float64
2017                                                                       221 non-null float64
Yes                                                                        221 non-null float64
Australia                                                                  221 non-null float64
Austria                                                                    221 non-null float64
Belgium                                                                    221 non-null float64
Brazil                                                                     221 non-null float64
Bulgaria                                                                   221 non-null float64
Canada                                                                     221 non-null float64
Chile                                                                      221 non-null float64
China                                                                      221 non-null float64
Croatia                                                                    221 non-null float64
Cyprus                                                                     221 non-null float64
Czech Republic                                                             221 non-null float64
Denmark                                                                    221 non-null float64
Egypt                                                                      221 non-null float64
Estonia                                                                    221 non-null float64
Finland                                                                    221 non-null float64
France                                                                     221 non-null float64
Germany                                                                    221 non-null float64
Greece                                                                     221 non-null float64
Hong Kong, China                                                           221 non-null float64
Hungary                                                                    221 non-null float64
Iceland                                                                    221 non-null float64
India                                                                      221 non-null float64
Indonesia                                                                  221 non-null float64
Iran, Islamic Republic of                                                  221 non-null float64
Ireland                                                                    221 non-null float64
Israel                                                                     221 non-null float64
Italy                                                                      221 non-null float64
Japan                                                                      221 non-null float64
Korea, Republic of                                                         221 non-null float64
Latvia                                                                     221 non-null float64
Lithuania                                                                  221 non-null float64
Luxembourg                                                                 221 non-null float64
Malaysia                                                                   221 non-null float64
Malta                                                                      221 non-null float64
Mexico                                                                     221 non-null float64
Morocco                                                                    221 non-null float64
Netherlands                                                                221 non-null float64
New Zealand                                                                221 non-null float64
Nigeria                                                                    221 non-null float64
Norway                                                                     221 non-null float64
Philippines                                                                221 non-null float64
Poland                                                                     221 non-null float64
Portugal                                                                   221 non-null float64
Romania                                                                    221 non-null float64
Russian Federation                                                         221 non-null float64
Singapore                                                                  221 non-null float64
Slovakia                                                                   221 non-null float64
Slovenia                                                                   221 non-null float64
South Africa                                                               221 non-null float64
Spain                                                                      221 non-null float64
Sweden                                                                     221 non-null float64
Switzerland                                                                221 non-null float64
Taipei, Chinese                                                            221 non-null float64
Thailand                                                                   221 non-null float64
Turkey                                                                     221 non-null float64
United States of America                                                   221 non-null float64
Uruguay                                                                    221 non-null float64
Venezuela, Bolivarian Republic of                                          221 non-null float64
FDI                                                                        221 non-null float64
dtypes: float64(95)
memory usage: 165.8 KB

In [8]:
for col_name in ["Administrative_and_support_service_activities","Advertising_and_market_research",
                 "Architectural_and_engineering_activities_technical_testing_and_analysis", 
                 "Computer_programming_consultancy_and_related_activities","Construction", 
                 "Education","Extraction_of_crude_petroleum_and_natural_gas","Information_and_communication",
                 "Legal_and_accounting_activities","Management_consultancy_activities",
                 "Manufacture_of_chemicals_and_chemical_products", "Manufacture_of_computer_electronic_and_optical_products",
                 "Manufacture_of_food_products","Manufacture_of_motor_vehicles_trailers_and_semi_trailers",
                 "Mining_and_quarrying","Professional_scientific_and_technical_activities","Real_estate_activities",
                 "Scientific_research_and_development","Telecommunications","Transportation_and_storage",
                 "Wholesale_and_retail_trade_and_repair_of_motor_vehicles_and_motorcycles"]:
                 
    
    del model_train[col_name]
    del model_test[col_name]

In [9]:
model_train.head()

,Real_GDP,Exchange_Rate,Long_Term_Interest_Rates,Current_Account_Balance,Unemployment_Rate,Inflation,Population,Corporate_Tax_Rate,Trade_Openess,Financial_and_insurance_activities,...,Spain,Sweden,Switzerland,"Taipei, Chinese",Thailand,Turkey,United States of America,Uruguay,"Venezuela, Bolivarian Republic of",FDI
31,0.630904,-0.458109,0.039306,-0.660447,-0.272349,-1.426685,0.008478,-0.434879,-1.364292,4.069531,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,680.35
64,-0.977965,0.882495,-1.055125,-0.489710,-0.718707,-0.688653,0.782246,-0.434879,-0.431557,4.069531,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,0.00
78,0.630904,-0.458109,0.039306,-0.660447,-0.272349,-1.426685,0.008478,-0.434879,-1.364292,4.069531,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,1215.80
85,-1.074346,1.448440,-1.182601,1.933870,-1.142748,1.279434,1.346033,-1.175126,1.339870,4.069531,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,-0.68
86,0.630904,-0.458109,0.039306,-0.660447,-0.272349,-1.426685,0.008478,-0.434879,-1.364292,4.069531,...,-0.148737,-0.156688,-0.150537,-0.094011,-0.09118,-0.098109,-0.160107,-0.089733,-0.09118,0.00

In [10]:
# drop labels for training set, but keep all others
Xtrain = model_train.drop("FDI", axis=1)

ytrain = model_train["FDI"].copy()

# Baseline

In [11]:
mean_FDI = ytrain.mean()
mean_FDI

418.16090497737554

In [12]:
from sklearn.metrics import mean_squared_error

# yhat will have the same number of rows as ytrain, 
# each cell will be filled with the same value, median_price
yhat = np.full((ytrain.shape[0], 1), mean_FDI)

baseline_mse = mean_squared_error(ytrain, yhat)

# take square root
baseline_rmse = np.sqrt(baseline_mse)

baseline_rmse

2529.7722737566633

# Random Forest

In [13]:
from sklearn.model_selection import GridSearchCV
import time
from sklearn.ensemble import RandomForestRegressor

rf_reg = RandomForestRegressor(random_state=7)

# specify the hyperparameters and their values
# 3 x 3 x 3 x 3 x 3 = 243 combinations in the grid 

param_grid = {
    'n_estimators': [5, 10, 20],
    'max_depth': [1, 2, 3],
    'min_samples_split': [1.0, 2, 3],
    'max_features': [0.1, 0.2, "auto"], 
    'min_samples_leaf': [1, 2, 3]
    
    
    
    
    
    

    
}

# we'll use 10-fold cross-validation
grid_search = GridSearchCV(rf_reg, param_grid, cv=10,
                           scoring='neg_mean_squared_error', 
                           return_train_score=True)

start = time.time()
grid_search.fit(Xtrain, ytrain)
end = time.time() - start
print(f"Took {end} seconds")

Took 51.133821964263916 seconds

C:\Intel\Python\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

In [14]:
grid_search.best_estimator_

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=2,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=7, verbose=0,
                      warm_start=False)

In [15]:
np.sqrt(-grid_search.best_score_)

679.9235993476307

In [16]:
val_scores = grid_search.cv_results_["mean_test_score"]
train_scores = grid_search.cv_results_["mean_train_score"]
params = [str(x) for x in grid_search.cv_results_["params"]]

for val_score, train_score, param in sorted(zip(val_scores, train_scores, params), reverse=True):
    print(np.sqrt(-val_score), np.sqrt(-train_score), param)

TypeError: '<' not supported between instances of 'dict' and 'dict'

In [17]:
# put them into a separate variable for convenience
feature_importances = grid_search.best_estimator_.feature_importances_

# the order of the features in `feature_importances` is the same as in the Xtrain dataframe,
# so we can "zip" the two and print in the descending order:

for k, v in sorted(zip(feature_importances, Xtrain.columns), reverse=True):
    print(f"{v}: {k}")

United States of America: 0.9461902526915076
Current_Account_Balance: 0.010288776445797346
Yes: 0.009665898935197006
Japan: 0.008001095518972469
Real_GDP: 0.006520098870044201
Population: 0.005541518738242169
Corporate_Tax_Rate: 0.0052059482631601735
Trade_Openess: 0.004195778619177982
Unemployment_Rate: 0.0030009899245138118
Spain: 0.0012665611576241484
Australia: 0.000123080835763254
Venezuela, Bolivarian Republic of: 0.0
Uruguay: 0.0
Turkey: 0.0
Thailand: 0.0
Taipei, Chinese: 0.0
Switzerland: 0.0
Sweden: 0.0
South Africa: 0.0
Slovenia: 0.0
Slovakia: 0.0
Singapore: 0.0
Russian Federation: 0.0
Romania: 0.0
Portugal: 0.0
Poland: 0.0
Philippines: 0.0
Norway: 0.0
Nigeria: 0.0
New Zealand: 0.0
Netherlands: 0.0
Morocco: 0.0
Mexico: 0.0
Malta: 0.0
Malaysia: 0.0
Luxembourg: 0.0
Long_Term_Interest_Rates: 0.0
Lithuania: 0.0
Latvia: 0.0
Korea, Republic of: 0.0
Italy: 0.0
Israel: 0.0
Ireland: 0.0
Iran, Islamic Republic of: 0.0
Inflation: 0.0
Indonesia: 0.0
India: 0.0
Iceland: 0.0
Hungary: 0.0
Hong Kong, China: 0.0
Greece: 0.0
Germany: 0.0
France: 0.0
Finland: 0.0
Financial_and_insurance_activities: 0.0
Exchange_Rate: 0.0
Estonia: 0.0
Egypt: 0.0
Denmark: 0.0
Czech Republic: 0.0
Cyprus: 0.0
Croatia: 0.0
China: 0.0
Chile: 0.0
Canada: 0.0
Bulgaria: 0.0
Brazil: 0.0
Belgium: 0.0
Austria: 0.0
2017: 0.0
2016: 0.0
2015: 0.0
2014: 0.0

# Test evaluation

In [23]:
# drop labels for training set, but keep all others
Xtest = model_test.drop("FDI", axis=1)
ytest = model_test["FDI"].copy()

best_model = grid_search.best_estimator_

yhat = best_model.predict(Xtest)

final_mse = mean_squared_error(ytest, yhat)
final_rmse = np.sqrt(final_mse)
final_rmse

254.16025481265768

In [24]:
# put them into a separate variable for convenience
feature_importances = grid_search.best_estimator_.feature_importances_

# the order of the features in `feature_importances` is the same as in the Xtrain dataframe,
# so we can "zip" the two and print in the descending order:

for k, v in sorted(zip(feature_importances, Xtest.columns), reverse=True):
    print(f"{v}: {k}")

United States of America: 0.9461902526915076
Current_Account_Balance: 0.010288776445797346
Yes: 0.009665898935197006
Japan: 0.008001095518972469
Real_GDP: 0.006520098870044201
Population: 0.005541518738242169
Corporate_Tax_Rate: 0.0052059482631601735
Trade_Openess: 0.004195778619177982
Unemployment_Rate: 0.0030009899245138118
Spain: 0.0012665611576241484
Australia: 0.000123080835763254
Venezuela, Bolivarian Republic of: 0.0
Uruguay: 0.0
Turkey: 0.0
Thailand: 0.0
Taipei, Chinese: 0.0
Switzerland: 0.0
Sweden: 0.0
South Africa: 0.0
Slovenia: 0.0
Slovakia: 0.0
Singapore: 0.0
Russian Federation: 0.0
Romania: 0.0
Portugal: 0.0
Poland: 0.0
Philippines: 0.0
Norway: 0.0
Nigeria: 0.0
New Zealand: 0.0
Netherlands: 0.0
Morocco: 0.0
Mexico: 0.0
Malta: 0.0
Malaysia: 0.0
Luxembourg: 0.0
Long_Term_Interest_Rates: 0.0
Lithuania: 0.0
Latvia: 0.0
Korea, Republic of: 0.0
Italy: 0.0
Israel: 0.0
Ireland: 0.0
Iran, Islamic Republic of: 0.0
Inflation: 0.0
Indonesia: 0.0
India: 0.0
Iceland: 0.0
Hungary: 0.0
Hong Kong, China: 0.0
Greece: 0.0
Germany: 0.0
France: 0.0
Finland: 0.0
Financial_and_insurance_activities: 0.0
Exchange_Rate: 0.0
Estonia: 0.0
Egypt: 0.0
Denmark: 0.0
Czech Republic: 0.0
Cyprus: 0.0
Croatia: 0.0
China: 0.0
Chile: 0.0
Canada: 0.0
Bulgaria: 0.0
Brazil: 0.0
Belgium: 0.0
Austria: 0.0
2017: 0.0
2016: 0.0
2015: 0.0
2014: 0.0

# Reduction in RMSE rate

In [28]:
100*(baseline_rmse - final_rmse)/baseline_rmse

89.95323581299141